version: '3.8'

services:
  maintenance-page:
    build: .
    container_name: tech-community-maintenance
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    networks:
      - maintenance-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  maintenance-network:
    driver: bridge